apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-service-app
  labels:
    app: accounts-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: accounts-service-app
  template:
    metadata:
      labels:
        app: accounts-service-app
    spec:
      containers:
        - name: accounts-service-app
          image: 3d3naj/account-service:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8282
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/accounts
            - name: REDIS_HOST
              value: redis

---

apiVersion: v1
kind: Service
metadata:
  name: accounts-service-svc
spec:
  selector:
    app: accounts-service-app
  ports:
  - port: 80
    targetPort: 8282
