apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-app
  labels:
    app: notification-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service-app
  template:
    metadata:
      labels:
        app: notification-service-app
    spec:
      containers:
        - name: notification-service-app
          image: djff94/final-notification-service:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 8289
          env:
            - name: KAFKA_SERVER
              value: kafka-broker:9092

---

apiVersion: v1
kind: Service
metadata:
  name: notification-service-svc
spec:
  selector:
    app: notification-service-app
  ports:
  - port: 80
    targetPort: 8289
