apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service-app
  labels:
    app: payment-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service-app
  template:
    metadata:
      labels:
        app: payment-service-app
    spec:
      containers:
      - name: payment-service-app
        image: djff94/final-payment-service:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        ports:
          - containerPort: 9696
        env:
          - name: MONGO_URL
            value: mongodb://mongo:27017/orders
          - name: EUREKA_URI
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: eureka-uri
          - name: S2S_LOCAL_TOKEN
            value: YXBpLXNlcnZpY2UtYWNjb3VudDpwd2QkMjAyMQ==
          - name: KAFKA_SERVER
            value: kafka-broker:9092
          - name: ZIPKIN_URL
            value: http://zipkin:9411/
          - name: CARD_PAYMENT_URI
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: card-service-uri
          - name: BANK_PAYMENT_URI
            valueFrom:
              configMapKeyRef:
                name: app-config
                key: bank-service-uri
---

apiVersion: v1
kind: Service
metadata:
  name: payment-service-svc
spec:
  selector:
    app: payment-service-app
  ports:
  - port: 80
    targetPort: 9696

