apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service-app
  labels:
    app: shipping-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shipping-service-app
  template:
    metadata:
      labels:
        app: shipping-service-app
    spec:
      containers:
      - name: shipping-service-app
        image: djff94/shipping-service:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "0.2"
        ports:
          - containerPort: 8383
        env:
          - name: MONGO_URL
            value: mongodb://mongo:27017/orders
          - name: KAFKA_SERVER
            value: kafka-broker:9092
          - name: ZIPKIN_URL
            value: http://zipkin:9411/
          - name: EUREKA_URI
            valueFrom:
              configMapKeyRef:
                name: eureka-uri
                key: key

---

apiVersion: v1
kind: Service
metadata:
  name: shipping-service-svc
spec:
  selector:
    app: shipping-service-app
  ports:
  - port: 80
    targetPort: 8383

