#handle cors
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[**]':
            allowedOrigins: "*"
<<<<<<< HEAD
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - OPTIONS
              - PUT
              - DELETE
=======
            allowedMethods: "*"
            allowedHeaders: "*"
>>>>>>> 54d91a19059099ec8ef8d9f535aa22421119cc0d
