spring:
  application:
    name: BANK-SERVICE
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411/}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

server:
  port: 0


